# Site settings
title: The Future--Decoded
header-img: img/home-bg.png
email: asheleymcdonald@gmail.com
copyright_name: mochacaremel
description: > # this means to ignore newlines until "baseurl:"
  Always Testing and Debugging
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mochacaremel
learn_profile: mochacaremel
email_username: asheleymcdonald@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
